# Generated by Django 2.0.7 on 2018-07-16 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('idclub', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('department', models.CharField(blank=True, max_length=45, null=True)),
                ('stadename', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('creationdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('idcoach', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('idCompetition', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'competition',
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'composition',
            },
        ),
        migrations.CreateModel(
            name='CompositionDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('button', models.IntegerField(blank=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('is_sub', models.IntegerField(blank=True, default=0)),
                ('composition', models.ForeignKey(blank=True, db_column='composition', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='statia.Composition')),
            ],
            options={
                'db_table': 'composition_details',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('idmatch', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('day', models.CharField(blank=True, max_length=45, null=True)),
                ('home_goal', models.IntegerField(null=True)),
                ('away_goal', models.IntegerField(null=True)),
                ('state', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('idplayer', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('picture', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=45, null=True)),
                ('foot', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('mail', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('incharge_name', models.CharField(blank=True, max_length=45, null=True)),
                ('incharge_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('incharge_mail', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('cote', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'poste',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('firstname', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profil',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StatiaPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statia_players',
            },
        ),
        migrations.CreateModel(
            name='StatistiquesMatch',
            fields=[
                ('idStatistiquesMatch', models.AutoField(primary_key=True, serialize=False)),
                ('possession', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fautes_subie', models.IntegerField()),
                ('penaltys_obtenue', models.IntegerField()),
                ('corners_obtenue', models.IntegerField()),
                ('ballons_concedes', models.IntegerField()),
                ('hors_jeux', models.IntegerField()),
                ('nombre_tirs', models.IntegerField()),
                ('tirs_cadres', models.IntegerField()),
                ('tirs_contres', models.IntegerField()),
                ('buts_inscrits', models.IntegerField()),
                ('buts_jeux', models.IntegerField()),
                ('buts_penalty', models.IntegerField()),
                ('buts_arretes', models.IntegerField()),
                ('passes_tente', models.IntegerField()),
                ('passe_reussis', models.IntegerField()),
                ('centre_tente', models.IntegerField()),
                ('centre_reussis', models.IntegerField()),
                ('match', models.ForeignKey(blank=True, db_column='match', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Match')),
            ],
            options={
                'db_table': 'stats_match',
            },
        ),
        migrations.CreateModel(
            name='StatistiquesPlayer',
            fields=[
                ('idStatistiquesPlayer', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField()),
                ('temps_de_jeu', models.IntegerField()),
                ('tirs_cadres', models.IntegerField()),
                ('tirs_tentes', models.IntegerField()),
                ('buts_marques', models.IntegerField()),
                ('passes_decisives', models.IntegerField()),
                ('fautes_commises', models.IntegerField()),
                ('carton_rouge', models.IntegerField()),
            ],
            options={
                'db_table': 'stats_player',
            },
        ),
        migrations.CreateModel(
            name='StatsPlayerMatch',
            fields=[
                ('idstats_player_match', models.AutoField(primary_key=True, serialize=False)),
                ('match', models.ForeignKey(blank=True, db_column='match', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Player')),
                ('player', models.ForeignKey(blank=True, db_column='player', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Player')),
            ],
            options={
                'db_table': 'stats_player_match',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('idteam', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('club', models.ForeignKey(blank=True, db_column='club', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Club')),
                ('league', models.ForeignKey(blank=True, db_column='match', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.League')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('idtypeuser', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'typeuser',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('idvideo', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=45, null=True)),
                ('match', models.ForeignKey(blank=True, db_column='match', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Match')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.AddField(
            model_name='statistiquesmatch',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='away',
            field=models.ForeignKey(blank=True, db_column='away', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home',
            field=models.ForeignKey(blank=True, db_column='home', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, db_column='competition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Competition'),
        ),
        migrations.AddField(
            model_name='compositiondetail',
            name='player',
            field=models.ForeignKey(blank=True, db_column='player', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Player'),
        ),
        migrations.AddField(
            model_name='compositiondetail',
            name='poste',
            field=models.ForeignKey(blank=True, db_column='poste', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Poste'),
        ),
        migrations.AddField(
            model_name='composition',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
