# Generated by Django 2.0.7 on 2018-07-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statia', '0002_auto_20180717_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
