# Generated by Django 2.0.7 on 2018-07-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statia', '0003_auto_20180717_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEventGoalkeeper',
            fields=[
                ('idMatchEvent', models.AutoField(primary_key=True, serialize=False)),
                ('minute', models.IntegerField()),
                ('player', models.ForeignKey(blank=True, db_column='player', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Player')),
                ('statsMatch', models.ForeignKey(blank=True, db_column='statsMatch', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.StatistiquesMatch')),
            ],
            options={
                'db_table': 'match_event_goal',
            },
        ),
        migrations.CreateModel(
            name='MatchEventPlayer',
            fields=[
                ('idMatchEvent', models.AutoField(primary_key=True, serialize=False)),
                ('minute', models.IntegerField()),
                ('lastpassPlayer', models.ForeignKey(blank=True, db_column='lastpassPlayer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Player')),
                ('player', models.ForeignKey(blank=True, db_column='player', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.Player')),
                ('statsMatch', models.ForeignKey(blank=True, db_column='statsMatch', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statia.StatistiquesMatch')),
            ],
            options={
                'db_table': 'match_event_player',
            },
        ),
    ]
