# Generated by Django 2.0.7 on 2018-07-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statia', '0004_matcheventgoalkeeper_matcheventplayer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matcheventgoalkeeper',
            table='matcheventgoal',
        ),
        migrations.AlterModelTable(
            name='matcheventplayer',
            table='matcheventplayer',
        ),
        migrations.AlterModelTable(
            name='statistiquesmatch',
            table='statsmatch',
        ),
    ]
