# Generated by Django 2.0.7 on 2018-07-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statia', '0005_auto_20180717_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='ballons_concedes',
            new_name='ballon_concede',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='buts_arretes',
            new_name='centre_rate',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='buts_inscrits',
            new_name='centre_reussi',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='buts_jeux',
            new_name='corner_obtenu',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='buts_penalty',
            new_name='degagement',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='centre_reussis',
            new_name='duel_gagne',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='centre_tente',
            new_name='duel_perdu',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='corners_obtenue',
            new_name='faute_commise',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='fautes_subie',
            new_name='hors_jeu',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='hors_jeux',
            new_name='interception',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='nombre_tirs',
            new_name='passe_ratee',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='passe_reussis',
            new_name='passe_reussie',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='passes_tente',
            new_name='penalty_commis',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='penaltys_obtenue',
            new_name='tir_cadre',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='tirs_cadres',
            new_name='tir_contre',
        ),
        migrations.RenameField(
            model_name='statistiquesmatch',
            old_name='tirs_contres',
            new_name='tir_hors_cadre',
        ),
        migrations.AddField(
            model_name='matcheventgoalkeeper',
            name='action',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
