# Generated by Django 2.0.7 on 2018-07-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statia', '0006_auto_20180717_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcheventplayer',
            name='event',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
