# Generated by Django 2.0.7 on 2018-10-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statia', '0008_auto_20180717_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matcheventplayer',
            name='event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
