# Generated by Django 2.0.7 on 2018-10-02 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statia', '0009_auto_20181001_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='Analyst',
        ),
        migrations.AlterModelTable(
            name='analyst',
            table='analyst',
        ),
    ]
